templates:
  - "templates/postgres.template.yml"
  - "templates/redis.template.yml"
  - "templates/sidekiq.template.yml"
  - "templates/web.template.yml"

expose:
  - "80:80"   # fwd host port 80   to container port 80 (http)
  - "2222:22" # fwd host port 2222 to container port 22 (ssh)
env:
  LANG: en_US.UTF-8
  HOSTNAME: "intercity.example.com"
  FROM_EMAIL: "example@example.com"

  SMTP_ADDRESS: smtp.example.com         # (mandatory)
  #SMTP_PORT: 587                        # (optional)
  #SMTP_USER_NAME: user@example.com      # (optional)
  #SMTP_PASSWORD: pa$$word               # (optional, WARNING the char '#' in pw can cause problems!)
  #SMTP_ENABLE_START_TLS: true           # (optional, default true)
  #SMTP_DOMAIN:                          # (optional, If not provided we use the HOSTNAME)

params:
  # Which Git revision should container use?
  version: master

## These containers are stateless, all data is stored in /shared
volumes:
  - volume:
      host: /var/intercity/shared/
      guest: /shared
  - volume:
      host: /var/intercity/shared/log/var-log
      guest: /var/log

run:
  - exec: echo "Beginning of custom commands"
  # Add your custom commands here
  - exec: echo "End of custom commands"
  - exec: awk -F\# '{print $1;}' ~/.ssh/authorized_keys | awk 'BEGIN { print "Authorized SSH keys for this container:"; } NF>=2 {print $NF;}'
