templates:
  - "templates/postgres.template.yml"
  - "templates/redis.template.yml"
  - "templates/sidekiq.template.yml"
  - "templates/web.template.yml"
  #- "templates/web.ssl.template.yml"
  #- "templates/web.letsencrypt.ssl.template.yml"

expose:
  - "80:80"   # fwd host port 80   to container port 80 (http)
  - "2222:22" # fwd host port 2222 to container port 22 (ssh)
  - "443:443" # fwd host port 443 to container port 443 (https)
env:
  LANG: en_US.UTF-8
  HOSTNAME: "intercity.example.com"
  LETSENCRYPT_ACCOUNT_EMAIL: "example@example.com"

params:
  # Which Git revision should container use?
  version: stable

## These containers are stateless, all data is stored in /shared
volumes:
  - volume:
      host: /var/intercity/shared/
      guest: /shared
  - volume:
      host: /var/intercity/shared/log/var-log
      guest: /var/log

run:
  - exec: echo "Beginning of custom commands"
  # Add your custom commands here
  - exec: echo "End of custom commands"
  - exec: awk -F\# '{print $1;}' ~/.ssh/authorized_keys | awk 'BEGIN { print "Authorized SSH keys for this container:"; } NF>=2 {print $NF;}'
